networks:
  adguardnetwork:
    name: adguardnetwork
    ipam:
      config:
        - subnet: ${ADGUARD_SUBNET:-172.39.5.0/24}

services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:v0.107.77@sha256:e6f2b8bcda06064ab055b44933a4f0e983c35558b9cdb8d2e7ab1efcee36d890
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - "${ADGUARD_DNS_PORT:-53}:53/tcp"
      - "${ADGUARD_DNS_PORT:-53}:53/udp"
      - "${ADGUARD_HTTP_PORT:-3005}:3000/tcp"
    volumes:
      - ./data/work:/opt/adguardhome/work
      - ./data/conf:/opt/adguardhome/conf
    networks:
      adguardnetwork:
        ipv4_address: ${ADGUARD_IP:-172.39.5.2}
