services:
  cloudflared:
    container_name: cloudflare-tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxynetwork

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "8080:80"    # HTTP (proxied traffic)
      - "8443:443"   # HTTPS (proxied traffic)
      - "8181:81"    # NPM admin UI (default)
    volumes:
      - ./data/nginx-proxy-manager/data:/data
      - ./data/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - proxynetwork
      - servarrnetwork
      - analyticsnetwork
      - monitoringnetwork
      - documentsnetwork
      - terminalnetwork
      - homepagenetwork

networks:
  proxynetwork:
    name: proxynetwork
  servarrnetwork:
    external: true
  analyticsnetwork:
    external: true
  monitoringnetwork:
    external: true
  documentsnetwork:
    external: true
  terminalnetwork:
    external: true
  homepagenetwork:
    external: true
